config/routes.rb
MagLite::Application.routes.draw do

  root :to => 'static_pages#root'
  get 'plans' => 'static_pages#plans'

  resource :signup, only: [:new, :create], path: 'subscribe'

  get   'login'  => 'sessions#new'
  post  'login'  => 'sessions#create'
  match 'logout' => 'sessions#destroy'

  resource :user, only: [:show, :edit, :update], path: 'profile'

  resources :lessons, only: [:index, :show]

  namespace :admin do
    root :to => 'dashboards#show', :as => :dashboard

    resources :lessons
    resources :users, :only => [:index]
  end

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base

  belongs_to :uploader, :class_name => "User"

  has_many :videos, :dependent => :destroy
  has_one :current_video, :order => "videos.id DESC", :class_name => "Video"

  attr_accessible :name, :description, :display_order, :published

  validates_presence_of :name, :description
  validates_uniqueness_of :display_order, :if => :published?
  validates_numericality_of :display_order, :greater_than => 0, :if => :published?
true
  scope :published, where(:published => true)
  scope :ordered, order("`#{self.table_name}`.`display_order` ASC")

  # Filter this relation to find records that can be viewed by a group
  #
  # user_group - User::Group to filter the lessons by
  #
  # Returns the filtered relation
  def self.viewable_by(user_group)
    if user_group.admin?
      self
    else
      self.published
    end
  end

  def next_lesson(lessons)
    lessons.ordered.where(['display_order > ?', display_order]).first
  end

end

app/controllers/admin/lessons_controller.rb
class Admin::LessonsController < Admin::ApplicationController

  def index
    @lessons = Lesson.all
  end

  def show
    @lesson = Lesson.find(params[:id])
  end

  def new
    @lesson = Lesson.new(params[:lesson])
  end

  def create
    @lesson = Lesson.new(params[:lesson])

    if @lesson.save
      redirect_to admin_lesson_path(@lesson), :notice => 'Lesson created'
    else
      render :action => :new
    end
  end

  def edit
    @lesson = Lesson.find(params[:id])
  end

  def update
    @lesson = Lesson.find(params[:id])

    if @lesson.update_attributes(params[:lesson])
      redirect_to admin_lesson_path(@lesson), :notice => 'Lesson updated'
    else
      render :action => :edit
    end
  end

  def destroy
    @lesson = Lesson.find(params[:id])

    if @lesson.destroy
      redirect_to admin_lessons_path, :notice => 'Lesson deleted'
    else
      render :action => :show
    end
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  before_filter :login_required

  def index
    @lessons = collection.all
  end

  def show
    @lesson = collection.find(params[:id])
  end

  protected

  def collection
    Lesson.viewable_by(current_user.group)
  end
  helper_method :collection

end

app/helpers/admin/lessons_helper.rb
module Admin::LessonsHelper

  def lesson_status_label(lesson)
    if lesson.published?
      content_tag :span, 'published', :class => 'label label-success'
    else
      content_tag :span, 'draft', :class => 'label label-default'
    end
  end

end

app/views/admin/lessons/_form.html.erb
<% if @lesson.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <strong>Oops!</strong>
    <%= @lesson.errors.full_messages.to_sentence %>
  </div>
<% end %>

<%= form_for [:admin, @lesson] do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, :class => "form-control", :rows => 3 %>
  </div>
  <div class="form-group">
    <%= f.label :display_order %>
    <%= f.number_field :display_order, :class => "form-control" %>
    <div class="help-block">
      Lessons are sorted in ascending order
    </div>
  </div>
  <div class="form-group">
    <div class="checkbox">
      <%= f.label :published do %>
        <%= f.check_box :published %> Published
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <% if @lesson.new_record? %>
      <%= f.submit "Create Lesson", :class => 'btn btn-success' %>
      <%= link_to 'Cancel', admin_lessons_path, :class => 'btn btn-link' %>
    <% else %>
      <%= f.submit "Update Lesson", :class => 'btn btn-success' %>
      <%= link_to 'Cancel', admin_lesson_path(@lesson), :class => 'btn btn-link' %>
    <% end %>
  </div>
<% end %>

app/views/admin/lessons/edit.html.erb
<% provide :title, 'Edit Lesson' %>

<div class="page-header">
  <h1><%= yield :title %></h1>
</div>

<%= render :partial => 'form' %>

app/views/admin/lessons/index.html.erb
<% provide :title, 'Manage Lessons' %>

<div class="page-header">
  <h1><%= yield :title %></h1>
</div>


<table class="table">
  <thead>
    <tr>
      <th>Lesson</th>
      <th>Order</th>
      <th>Status</th>
      <th>Created</th>
    </tr>
  </thead>
  <tbody>
    <% if @lessons.any? %>
      <% @lessons.each do |lesson| %>
        <tr>
          <td>
            <strong><%= link_to lesson.name, admin_lesson_path(lesson) %></strong>
            <br>
            <small><%= truncate lesson.description, :length => 60 %></small>
          </td>
          <td>
            <%= lesson.display_order %>
          </td>
          <td>
            <%= lesson_status_label(lesson) %>
          </td>
          <td>
            <%=l lesson.created_at.to_date %>
            <br>
            <small><%= time_ago_in_words lesson.created_at %> ago</small>
          </td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="4">
          <em>There aren't any lessons uploaded yet</em>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="4">
        <%= link_to 'New Lesson', new_admin_lesson_path, :class => 'btn btn-success' %>
      </td>
    </tr>
  </tfoot>
</table>

app/views/admin/lessons/new.html.erb
<% provide :title, 'New Lesson' %>

<div class="page-header">
  <h1><%= yield :title %></h1>
</div>

<%= render :partial => 'form' %>

app/views/admin/lessons/show.html.erb
<% provide :title, "Lesson \"#{@lesson.name}\"" %>

<div class="page-header">
  <h1><%= yield :title %></h1>
</div>

<div class="row">
  <div class="col-md-8">
    <h5>Status</h5>
    <p><%= lesson_status_label(@lesson) %></p>
  </div>
</div>

<div class="row">
  <div class="col-md-8">
  </div>
</div>



<%= render :partial => '/lessons/lesson', :object => @lesson %>

<p>
  <%= link_to 'Edit Lesson', edit_admin_lesson_path(@lesson), :class => 'btn btn-success' %>
  <%= link_to 'Return to List', admin_lessons_path, :class => 'btn btn-link' %>

  <%= link_to 'Delete Lesson', admin_lesson_path(@lesson), :method => :delete, :class => 'btn btn-danger pull-right' %>
</p>