config/routes.rb
MagLite::Application.routes.draw do

  root :to => 'static_pages#root'
  get 'plans' => 'static_pages#plans'

  resource :signup, only: [:new, :create], path: 'subscribe'

  get   'login'  => 'sessions#new'
  post  'login'  => 'sessions#create'
  match 'logout' => 'sessions#destroy'

  resource :user, only: [:show, :edit, :update], path: 'profile'

  resources :lessons, only: [:index, :show]

  namespace :admin do
    root :to => 'dashboards#show', :as => :dashboard

    resources :lessons
    resources :users, :only => [:index]
  end

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base

  belongs_to :uploader, :class_name => "User"

  has_many :videos, :dependent => :destroy
  has_one :current_video, :order => "videos.id DESC", :class_name => "Video"

  attr_accessible :name, :description, :display_order, :published

  validates_presence_of :name, :description
  validates_uniqueness_of :display_order, :if => :published?
  validates_numericality_of :display_order, :greater_than => 0, :if => :published?
true
  scope :published, where(:published => true)
  scope :ordered, order("`#{self.table_name}`.`display_order` ASC")

  # Filter this relation to find records that can be viewed by a group
  #
  # user_group - User::Group to filter the lessons by
  #
  # Returns the filtered relation
  def self.viewable_by(user_group)
    if user_group.admin?
      self
    else
      self.published
    end
  end

  def next_lesson(lessons)
    lessons.ordered.where(['display_order > ?', display_order]).first
  end

end

app/controllers/admin/lessons_controller.rb
class Admin::LessonsController < Admin::ApplicationController

  def index
    @lessons = Lesson.all
  end

  def show
    @lesson = Lesson.find(params[:id])
  end

  def new
    @lesson = Lesson.new(params[:lesson])
  end

  def create
    @lesson = Lesson.new(params[:lesson])

    if @lesson.save
      redirect_to admin_lesson_path(@lesson), :notice => 'Lesson created'
    else
      render :action => :new
    end
  end

  def edit
    @lesson = Lesson.find(params[:id])
  end

  def update
    @lesson = Lesson.find(params[:id])

    if @lesson.update_attributes(params[:lesson])
      redirect_to admin_lesson_path(@lesson), :notice => 'Lesson updated'
    else
      render :action => :edit
    end
  end

  def destroy
    @lesson = Lesson.find(params[:id])

    if @lesson.destroy
      redirect_to admin_lessons_path, :notice => 'Lesson deleted'
    else
      render :action => :show
    end
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  before_filter :login_required

  def index
    @lessons = collection.all
  end

  def show
    @lesson = collection.find(params[:id])
  end

  protected

  def collection
    Lesson.viewable_by(current_user.group)
  end
  helper_method :collection

end

app/helpers/admin/lessons_helper.rb
module Admin::LessonsHelper

  def lesson_status_label(lesson)
    if lesson.published?
      content_tag :span, 'published', :class => 'label label-success'
    else
      content_tag :span, 'draft', :class => 'label label-default'
    end
  end

end

app/views/lessons/_lesson.html.erb
<% if lesson.current_video %>
  <%= videojs_rails sources: {mp4: lesson.current_video.url}, width: 600, height: 450 %>
<% else %>
  <p>This lesson doesn't have a video.</p>
<% end %>

<p><%= lesson.description %></p>

app/views/lessons/_lesson_mini.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
      <%= link_to lesson_mini.name, lesson_path(lesson_mini) %>
      <small><%= lesson_mini.current_video.human_length %></small>
    </h3>
  </div>
  <div class="panel-body">
    <%= truncate lesson_mini.description, :length => 60 %>
  </div>
  <div class="panel-footer">
    <%= link_to 'View Lesson', lesson_path(lesson_mini), :class => 'btn btn-sm btn-success' %>
  </div>
</div>

app/views/lessons/index.html.erb
<% provide :title, "Lessons" %>

<div class="page-header">
  <h1><%= yield :title %></h1>
</div>

<% if @lessons.any? %>
  <div class="row">
    <% @lessons.each do |lesson| %>
      <div class="col-md-4">
        <%= render :partial => 'lesson_mini', :object => lesson %>
      </div>
    <% end %>
  </div>
<% else %>
  <p>
    There aren't any lessons for you to study...that's not very helpful at all :(
  </p>
<% end %>

app/views/lessons/show.html.erb
<%= provide :title, @lesson.name %>

<div class="page-header">
  <h1><%= yield :title %></h1>
</div>

<div class="row">
  <div class="col-md-8">
    <%= render :partial => 'lesson', :object => @lesson %>
  </div>
  <div class="col-md-4">
    <% if (next_lesson = @lesson.next_lesson(collection)) %>
      <h3>Next Lesson</h3>
      <%= render :partial => 'lesson_mini', :object => next_lesson %>
    <% else %>
      <p>
        <em>This is the last lesson</em>
      </p>
    <% end %>
    <p>
      <%= link_to "Return to Lessons", lessons_path, :class => 'btn btn-default' %>
    </p>
  </div>
</div>