config/routes.rb
MagLite::Application.routes.draw do

  root :to => 'static_pages#root'
  get 'plans' => 'static_pages#plans'

  resource :signup, only: [:new, :create], path: 'subscribe'

  get   'login'  => 'sessions#new'
  post  'login'  => 'sessions#create'
  match 'logout' => 'sessions#destroy'

  resource :user, only: [:show, :edit, :update], path: 'profile'

  resources :lessons, only: [:index, :show]

  namespace :admin do
    root :to => 'dashboards#show', :as => :dashboard

    resources :lessons
    resources :users, :only => [:index]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <link rel="shortcut icon" href="/favicon.ico" />

  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

  <div class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <%= link_to 'Mag-Lite', (if logged_in? then lessons_path else root_path end), :class => "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <% if admin? %>
            <li><%= link_to 'Admin', admin_dashboard_path %></li>
          <% end %>
          <% if logged_in? %>
            <li><%= link_to 'Lessons', lessons_path %></li>
          <% else %>
            <li><%= link_to 'About', root_path %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to 'Profile', user_path %></li>
            <li><%= link_to 'Logout', logout_path %></li>
          <% else %>
            <li><%= link_to 'Subscribe', new_signup_path %></li>
            <li><%= link_to 'Login', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>